import "../css/globals.css";
import React from "react";
import { RemindersProvider } from "../utils/RemindersContext";

export const metadata = {
  title: "Reminders Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RemindersProvider>{children}</RemindersProvider>
      </body>
    </html>
  );
}
